# Shared image for both the API and the demo (docker-compose.yml picks the
# command). Real data/model artifacts are NOT baked into the image -- they
# are gitignored, regenerated by `make data`/`make train`, and mounted in
# as volumes at runtime (see docker-compose.yml) rather than copied here,
# to avoid a multi-GB image for what's fundamentally reproducible local
# state.
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir -r requirements.txt

COPY roar/ roar/
COPY experiments/ experiments/
COPY demo/ demo/
COPY README.md ./
RUN pip install --no-cache-dir -e .

EXPOSE 8000 8501
