"""`make train`: fits the LightGBMPredictor on the Phase 1 feature table,
reports honest quality on the held-out temporal test split, and serializes a
versioned model artifact (CLAUDE.md rule 4: every reported number must be
regenerable from this one command; rule 2: the test split is never touched
during training, only for this final report).

Run directly: `python -m roar.predictor.train` (requires
`data/processed/features.parquet` from `make data`).
"""

from __future__ import annotations

import datetime as dt
import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from roar.graph.config import REPO_ROOT, load_config
from roar.graph.features import FEATURES_PATH
from roar.predictor.lightgbm import PREDICTOR_CONFIG_PATH, LightGBMPredictor

MODELS_DIR = REPO_ROOT / "results" / "models"
FIGURES_DIR = REPO_ROOT / "results" / "figures"
REPORT_PATH = REPO_ROOT / "results" / "predictor_report.md"


def plot_calibration(calibration: list[tuple[float, float]], path) -> None:
    nominal = [q for q, _ in calibration]
    empirical = [e for _, e in calibration]
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.plot([0, 1], [0, 1], linestyle="--", color="gray", label="perfect calibration")
    ax.plot(nominal, empirical, marker="o", color="C0", label="LightGBM speed quantiles")
    ax.set_xlabel("Nominal quantile")
    ax.set_ylabel("Empirical coverage (held-out temporal test split)")
    ax.set_title("Predictor calibration")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def write_report(version: str, metrics: dict, calibration_rel_path: str) -> None:
    with open(REPORT_PATH, "w") as f:
        f.write("# Predictor report (LightGBM)\n\n")
        f.write(
            f"Generated by `make train` -- model artifact: "
            f"`results/models/{version}/`.\n\n"
        )
        f.write("## Held-out temporal test-set quality\n\n")
        f.write(f"- Test rows: {metrics['n']}\n")
        f.write(f"- MAE: {metrics['mae_s']:.1f} s\n")
        f.write(f"- RMSE: {metrics['rmse_s']:.1f} s\n")
        f.write(f"- MAPE: {metrics['mape_pct']:.1f}%\n\n")
        f.write("## Quantile calibration (speed-space; see LightGBMPredictor.evaluate)\n\n")
        f.write("| Nominal quantile | Empirical coverage |\n|---|---|\n")
        for q, e in metrics["calibration"]:
            f.write(f"| {q} | {e:.3f} |\n")
        f.write(f"\n![calibration]({calibration_rel_path})\n")


def main() -> None:
    data_cfg = load_config()
    predictor_cfg = load_config(PREDICTOR_CONFIG_PATH)
    predictor_cfg.setdefault("time_bucket_minutes", data_cfg["time_bucket_minutes"])

    if not FEATURES_PATH.exists():
        raise FileNotFoundError(f"{FEATURES_PATH} not found. Run `make data` first.")

    print(f"Loading features from {FEATURES_PATH} ...")
    features_df = pd.read_parquet(FEATURES_PATH)

    print("Training LightGBM quantile models on the 'train' split "
          "(early-stopped against 'val') ...")
    predictor = LightGBMPredictor.train(features_df, cfg=predictor_cfg)

    test_df = features_df[features_df["split"] == "test"]
    print(f"Evaluating on the held-out 'test' split ({len(test_df)} rows, never seen "
          "during training) ...")
    metrics = predictor.evaluate(test_df)

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    calibration_path = FIGURES_DIR / "predictor_calibration.png"
    plot_calibration(metrics["calibration"], calibration_path)

    version = dt.datetime.now(dt.UTC).strftime("v%Y%m%d_%H%M%S")
    model_dir = MODELS_DIR / version
    predictor.save(model_dir)
    (MODELS_DIR / "latest.json").write_text(json.dumps({"version": version}, indent=2))

    write_report(version, metrics, "figures/predictor_calibration.png")

    print(f"Saved model to {model_dir}")
    print(f"Saved report to {REPORT_PATH}")
    print(
        f"MAE={metrics['mae_s']:.1f}s RMSE={metrics['rmse_s']:.1f}s "
        f"MAPE={metrics['mape_pct']:.1f}%"
    )


if __name__ == "__main__":
    main()
