"""Download and cache the real OSM drive network for the configured city.

Real data only: the graph comes from OpenStreetMap via OSMnx (Overpass API).
No edge attribute here is invented — `length_m` and `geometry` come straight
from OSM; `speed_limit_mph` and `lanes` fall back to the documented,
functional-class-based defaults in experiments/configs/data.yaml only when
OSM's own `maxspeed`/`lanes` tags are absent (real roads genuinely lack these
tags on OSM; defaulting to a signed-limit convention is standard practice,
not fabrication of measured data).

Run directly: `python -m roar.graph.load_graph`
"""

from __future__ import annotations

import re

import geopandas as gpd
import networkx as nx
import osmnx as ox

from roar.graph.config import REPO_ROOT, load_config

PROCESSED_DIR = REPO_ROOT / "data" / "processed"
GRAPH_PATH = PROCESSED_DIR / "la_drive_graph.graphml"
EDGES_PATH = PROCESSED_DIR / "edges.parquet"
DATA_QUALITY_REPORT = REPO_ROOT / "results" / "data_quality.md"

_SPEED_VALUE_RE = re.compile(r"(\d+(?:\.\d+)?)")


def _as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _parse_speed_mph(raw: str) -> float | None:
    s = str(raw).strip().lower()
    match = _SPEED_VALUE_RE.search(s)
    if not match:
        return None
    val = float(match.group(1))
    if "km/h" in s or "kmh" in s or "kph" in s:
        val *= 0.621371
    return val


def road_class_of(highway) -> str:
    values = _as_list(highway)
    return str(values[0]) if values else "unclassified"


def speed_limit_mph_of(maxspeed, highway, defaults: dict) -> float:
    for raw in _as_list(maxspeed):
        val = _parse_speed_mph(raw)
        if val is not None:
            return val
    return float(defaults.get(road_class_of(highway), defaults["default"]))


def lanes_of(lanes) -> int:
    values = []
    for raw in _as_list(lanes):
        try:
            values.append(int(float(raw)))
        except (TypeError, ValueError):
            continue
    return max(values) if values else 1


def download_graph(cfg: dict) -> nx.MultiDiGraph:
    bbox = cfg["osm"]["bbox"]
    return ox.graph_from_bbox(
        bbox=(bbox["north"], bbox["south"], bbox["east"], bbox["west"]),
        network_type=cfg["osm"]["network_type"],
    )


def build_edges_gdf(graph: nx.MultiDiGraph, cfg: dict) -> gpd.GeoDataFrame:
    defaults = cfg["osm"]["default_speed_mph"]
    edges = ox.graph_to_gdfs(graph, nodes=False, edges=True)
    edges = edges.reset_index()  # columns: u, v, key, ...

    edges["road_class"] = edges["highway"].apply(road_class_of)
    edges["speed_limit_mph"] = edges.apply(
        lambda r: speed_limit_mph_of(r.get("maxspeed"), r.get("highway"), defaults), axis=1
    )
    if "lanes" in edges.columns:
        edges["lanes"] = edges["lanes"].apply(lanes_of)
    else:
        edges["lanes"] = 1
    edges["length_m"] = edges["length"].astype(float)
    edges["edge_id"] = edges.apply(lambda r: f"{r['u']}_{r['v']}_{r['key']}", axis=1)

    keep_cols = [
        "edge_id",
        "u",
        "v",
        "key",
        "length_m",
        "road_class",
        "speed_limit_mph",
        "lanes",
        "geometry",
    ]
    return edges[keep_cols].set_geometry("geometry")


def largest_scc_fraction(graph: nx.MultiDiGraph) -> tuple[int, int, float]:
    n_nodes = graph.number_of_nodes()
    largest = max(nx.strongly_connected_components(graph), key=len)
    return len(largest), n_nodes, len(largest) / n_nodes if n_nodes else 0.0


def main() -> None:
    cfg = load_config()
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Downloading OSM drive network for bbox {cfg['osm']['bbox']} ...")
    graph = download_graph(cfg)
    print(f"Downloaded graph: {graph.number_of_nodes()} nodes, {graph.number_of_edges()} edges.")

    edges_gdf = build_edges_gdf(graph, cfg)
    ox.save_graphml(graph, filepath=GRAPH_PATH)
    edges_gdf.to_parquet(EDGES_PATH)

    scc_size, n_nodes, scc_fraction = largest_scc_fraction(graph)

    DATA_QUALITY_REPORT.parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_QUALITY_REPORT, "w") as f:
        f.write("# Data quality report\n\n")
        f.write(
            "Generated by `make data` (roar/graph/load_graph.py, map_sensors.py, "
            "features.py).\n\n"
        )
        f.write("## Road network (OpenStreetMap)\n\n")
        f.write(f"- Bounding box: {cfg['osm']['bbox']}\n")
        f.write(f"- Nodes: {graph.number_of_nodes()}\n")
        f.write(f"- Edges: {graph.number_of_edges()}\n")
        f.write(
            f"- Largest strongly connected component: {scc_size}/{n_nodes} nodes "
            f"({scc_fraction:.1%})\n"
        )

    print(f"Saved graph to {GRAPH_PATH}")
    print(f"Saved edges to {EDGES_PATH}")
    print(
        f"Largest SCC: {scc_size}/{n_nodes} nodes ({scc_fraction:.1%}) "
        f"-- see {DATA_QUALITY_REPORT}"
    )


if __name__ == "__main__":
    main()
